### PR TITLE
 Create paaka-yajjna-agnihotra-riitiH.md

### PR DESCRIPTION
**Pull request by vvasuki**

### CODE REVIEW

**Comment by aupasana** [comment]
Please omit the addition of new files to index.md until the files have been proofread at least once after the initial typesetting. There seem to be a number of obvious errors.

**Comment by vvasuki** [comment]
"Allow edits from maintainers." इति कृतमेव, येन स्वीकारात् पूर्वं भवान् परीक्षितुं शक्नोति। अत्र के दोषा इति न स्पष्टम्।

**Comment by vvasuki** [comment]
Also the point of code review is to ensure that such mistakes are weeded out as a result of the review. Better to not merge until you've satisfied yourself - rather than adding mistakes and then not indexing them.

**Comment by aupasana** [comment]
If you have made an honest effort to proofread once, I don't mind merging and then fixing errors over time. Otherwise, the pull requests will sit for a little while, until I am able to give them a once over.

The two errors that I saw from a quick once over are उपस्मृपृश्य and तां दर्भैरद्भिः प्रक्षलयेदिति. The previous pull request also had a number of obvious errors.

**Comment by vvasuki** [comment]
After I copy paste prayoga, I go over each word and remove loads of errors. Despite that, some do get left over, such as the ones you pointed to, and some I unwittingly introduce while typing. (I've noted quite a few such errors in the pages you've typed, which is why I asked for the "edit me" link. But of course, my error rate seems higher - likely due to screen daze.)

That said, unlike in mantra-s, such typo-s are not critical as far as vidhi-s are concerned. As the famous forward goes, "Aoccdrnig to rscheearch at Cmabrigde uinervtisy, it deosn’t mttaer waht oredr the ltteers in a wrod are, the olny iprmoetnt tihng is taht the frist and lsat ltteres are at the rghit pclae. The rset can be a tatol mses and you can sitll raed it wouthit a porbelm. Tihs is bcuseae we do not raed ervey lteter by it slef but the wrod as a wlohe."; and practitioners are used to abysmal transliterations such as [this](https://hindupad.com/sama-veda-uapakarma-procedure-sama-vedi-avani-avittam-puja-procedure-with-mantram-and-samkalpam/).

**Comment by aupasana** [comment]
Perfect, as long as an effort has been made, happy to accept them as is. Proofreading is not easy. As you've pointed out, the stuff I've pointed out is a perfect example. There is a "source" button on the top of each page which takes you to the relevant github page. Hopefully that serves as a "edit me" link as well, and you can point out / fix the errors when possible.

**Pull request merged**
